import { GameConfig } from "./game-types";

export const GAME_CONFIG: GameConfig = {
    time_budget: 20,
    athletes: [
        {
            id: "nora_quick",
            name: "Nora Quick",
            description: "Speed and endurance specialist",
            avatar: "/characters/nora.png",
            weights: {
                conditioning: 0.8,
                striking: 0.3,
                wrestling: 0.14,
                bjj: 0.06,
                muay_thai: 0.7,
                tactical: 0.4,
                recovery: 0.2,
            },
            bias_range: [-0.1, 0.2],
        },
        {
            id: "max_heavy",
            name: "Max Heavy",
            description: "Power and technique master",
            avatar: "/characters/max.png",
            weights: {
                conditioning: 0.3,
                striking: 0.9,
                wrestling: 0.49,
                bjj: 0.21,
                muay_thai: 0.2,
                tactical: 0.3,
                recovery: 0.2,
            },
            bias_range: [-0.05, 0.15],
        },
    ],
    opponents: [
        {
            id: 1,
            name: "Breather Bruno",
            description: "Cardio machine with stamina for days",
            avatar: "/characters/bruno.png",
            threshold: 8.0,
            stats: {
                conditioning: 0.9,
                striking: 0.4,
                wrestling: 0.21,
                bjj: 0.09,
                muay_thai: 0.7,
                tactical: 0.3,
                recovery: 0.5,
            },
        },
        {
            id: 2,
            name: "Twisty Tia",
            description: "Lightning-fast footwork specialist",
            avatar: "/characters/tia.png",
            threshold: 8.6,
            stats: {
                conditioning: 0.6,
                striking: 0.3,
                wrestling: 0.28,
                bjj: 0.12,
                muay_thai: 0.9,
                tactical: 0.4,
                recovery: 0.4,
            },
        },
        {
            id: 3,
            name: "Wall Hugo",
            description: "Unbreakable grappler with iron defense",
            avatar: "/characters/wall.png",
            threshold: 9.0,
            stats: {
                conditioning: 0.3,
                striking: 0.7,
                wrestling: 0.63,
                bjj: 0.27,
                muay_thai: 0.2,
                tactical: 0.3,
                recovery: 0.4,
            },
        },
        {
            id: 4,
            name: "Storm Rina",
            description: "Balanced fighter with no weaknesses",
            avatar: "/characters/rina.png",
            threshold: 9.2,
            stats: {
                conditioning: 0.7,
                striking: 0.8,
                wrestling: 0.35,
                bjj: 0.15,
                muay_thai: 0.6,
                tactical: 0.5,
                recovery: 0.3,
            },
        },
        {
            id: 5,
            name: "Sneak Nico",
            description: "Clever tactician with mental edge",
            avatar: "/characters/nico.png",
            threshold: 9.4,
            stats: {
                conditioning: 0.5,
                striking: 0.5,
                wrestling: 0.28,
                bjj: 0.12,
                muay_thai: 0.9,
                tactical: 0.8,
                recovery: 0.3,
            },
        },
        {
            id: 6,
            name: "Boss Kato",
            description: "Championship-level all-around master",
            avatar: "/characters/kato.png",
            threshold: 9.7,
            stats: {
                conditioning: 0.8,
                striking: 0.8,
                wrestling: 0.63,
                bjj: 0.27,
                muay_thai: 0.6,
                tactical: 0.7,
                recovery: 0.5,
            },
        },
    ],
};
